#Give sudo permission
sudo: required

#Use docker service
services:
  - docker

#build image before install
before_install:
  - docker build -t neal603319266/docker-react -f Dockerfile.dev .
  
#scripts to run for testing purpose
script:
  - docker run neal603319266/docker-react npm run test -- --coverage
  